from datetime import timedelta
from typing import Protocol


class KVStorage(Protocol):
    async def setex(self, key: str, expiration: timedelta, value: bytes | str) -> None: ...
    async def set(self, key: str, value: bytes | str) -> None: ...
    async def get(self, key: str) -> bytes | None: ...
