from pydantic import BaseModel, Field, model_validator

from core.utils.hash import hash_model


class AutoGeneratedId(BaseModel):
    id: str = Field(
        default="",
        description="The id, automatically computed based on properties",
    )

    def _excluded_fields(self):
        return {"id"}

    def _hashed_id(self):
        return hash_model(self, exclude_none=True, exclude=self._excluded_fields())

    @model_validator(mode="after")
    def validate_id(self):
        if not self.id:
            self.id = self._hashed_id()
        return self

    def reset_id(self):
        self.id = self._hashed_id()
