from typing import override

from core.domain._autogenerated_id import AutoGeneratedId
from core.domain.error import Error
from core.domain.message import Message


class AgentOutput(AutoGeneratedId):
    messages: list[Message] | None = None
    error: Error | None = None
    preview: str = ""

    @override
    def _excluded_fields(self):
        return {"id", "preview"}

    @property
    def has_tool_call_requests(self) -> bool:
        if not self.messages:
            return False
        return any(m.has_tool_call_request for m in self.messages)
