name: Main

on:
  push:
    branches:
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  backend-quality:
    uses: ./.github/workflows/.backend-quality.yml
    secrets: inherit

  web-quality:
    uses: ./.github/workflows/.web-quality.yml
    secrets: inherit

  build-ghcr-image-backend:
    needs: backend-quality
    uses: ./.github/workflows/.build-ghcr.yml
    secrets: inherit
    with:
      service: backend

  build-ghcr-image-web:
    needs: web-quality
    uses: ./.github/workflows/.build-ghcr.yml
    secrets: inherit
    with:
      service: web
