name: Production

on:
  push:
    branches:
      - production
      # TODO: remove when we don't want to deploy from main
      - main

permissions:
  contents: read
  id-token: write
  packages: write

jobs:
  deploy:
    uses: ./.github/workflows/.azure-build-deploy.yml
    secrets: inherit
    with:
      env: prod
